### ISSUE TITLE
Bug: Pretty printer fails on subtree

### ISSUE THREAD

**Issue by Sporarum** [epfl-lara/StainlessFit#41]
The error occured on https://github.com/Sporarum/StainlessFit/commit/b00f774e812ce9fd2d60ee740c7da28f536d3bfc
When running: `fit parteval examples/eval/fact.sf`

Here's the error log:
```
[FATAL] The pretty printer does not handle subtree: App(Bind(fac#7,Lambda(None,Bind(m#8,IfThenElse(Primitive(==,List(Var(m#8), NatLiteral(0))),NatLiteral(1),Primitive(*,List(Var(m#8), App(Var(fac#7),Primitive(-,List(Var(m#8), NatLiteral(1)))))))))),NatLiteral(10))
Exception in thread "main" java.lang.Exception: The pretty printer does not handle subtree: App(Bind(fac#7,Lambda(None,Bind(m#8,IfThenElse(Primitive(==,List(Var(m#8), NatLiteral(0))),NatLiteral(1),Primitive(*,List(Var(m#8), App(Var(fac#7),Primitive(-,List(Var(m#8), NatLiteral(1)))))))))),NatLiteral(10))
        at stainlessfit.core.util.Reporter.fatalError(Reporter.scala:22)
        at stainlessfit.core.trees.Printer$.$anonfun$asStringDebug$1(Printer.scala:236)
        at stainlessfit.core.trees.Printer$.$anonfun$asStringDebug$1$adapted(Printer.scala:234)
        at stainlessfit.core.trees.Tree$.traversePost(Trees.scala:248)
        at stainlessfit.core.trees.Tree$.$anonfun$traversePost$5(Trees.scala:301)
        at stainlessfit.core.trees.Tree$.$anonfun$traversePost$5$adapted(Trees.scala:301)
        at scala.collection.immutable.List.foreach(List.scala:305)
        at stainlessfit.core.trees.Tree$.traversePost(Trees.scala:301)
        at stainlessfit.core.trees.Tree$.traversePost(Trees.scala:241)
        at stainlessfit.core.trees.Tree.traversePost(Trees.scala:861)
        at stainlessfit.core.trees.Printer$.asStringDebug(Printer.scala:234)
        at stainlessfit.core.trees.Printer$.itToString(Printer.scala:168)
        at stainlessfit.core.trees.Printer$.$anonfun$exprAsString$2(Printer.scala:179)
        at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:434)
        at stainlessfit.core.trees.Printer$.$anonfun$exprAsString$1(Printer.scala:177)
        at stainlessfit.core.util.Bench.time(Bench.scala:25)
        at stainlessfit.core.trees.Printer$.exprAsString(Printer.scala:177)
        at stainlessfit.core.trees.Printer$.exprInfo(Printer.scala:241)
        at stainlessfit.core.partialEvaluator.PartialEvaluator$.evaluate(PartialEvaluator.scala:101)
        at stainlessfit.core.Core$.$anonfun$partEvalFile$1(Core.scala:71)
        at scala.util.Either.flatMap(Either.scala:352)
        at stainlessfit.core.Core$.partEvalFile(Core.scala:67)
        at stainlessfit.core.App.$anonfun$partEval$1(App.scala:54)
        at stainlessfit.core.util.FileWatcher$.watchable(FileWatcher.scala:103)
        at stainlessfit.core.App.partEval(App.scala:53)
        at stainlessfit.core.App.start(App.scala:38)
        at stainlessfit.core.App$.launch(App.scala:88)
        at stainlessfit.cli.Main$.$anonfun$main$1(Main.scala:23)
        at stainlessfit.cli.Main$.$anonfun$main$1$adapted(Main.scala:23)
        at scala.Option.foreach(Option.scala:437)
        at stainlessfit.cli.Main$.main(Main.scala:23)
        at stainlessfit.cli.Main.main(Main.scala)
```
Subtree when indented:
```
App(
  Bind(
    fac#7,
	Lambda(
	  None,
	  Bind(
		m#8,
		IfThenElse(
			Primitive(==,List(
				Var(m#8), 
				NatLiteral(0)
			)),
			NatLiteral(1),
			Primitive(*,List(
				Var(m#8), 
				App(
					Var(fac#7),
					Primitive(-,List(
						Var(m#8), 
						NatLiteral(1)
					))
				)
			))
		)
	  )
	)
  ),
  NatLiteral(10)
)
```

**Comment by jad-hamza** [comment]
Thanks for the report, I think the reason is that `Bind` should not appear as the first argument of `App` (which takes two "normal" trees as arguments)
